title: Aquarium Sensei
description: "Your smart companion for aquarium planning, monitoring, and care."
url: https://aquariumsensei.workingfromhome-ultd.com
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - LICENSE
