title: Aquarium Sensei
description: "Your smart companion for aquarium planning, monitoring, and care."
url: https://dmabamboo.github.io
baseurl: /aquarium-sensei-public

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - LICENSE
